#%RAML 1.0  DocumentationItem
title: PharmEasy
content: |
  ***PharmEasy*** is a application to purchase medicines or healthcare_products and diagnostic_tests
  Check out the [API Portal]() for more details.